name: Determine Next Color
description: Determine next deployment color
inputs:
  github-token:
    description: 'GitHub token for ghcr.io'
    required: true
outputs:
  NEW_COLOR:
    description: 'The color for the new deployment (blue/green)'
    value: ${{ steps.color.outputs.NEW_COLOR }}
  OLD_COLOR:
    description: 'The color of the current deployment (blue/green)'
    value: ${{ steps.color.outputs.OLD_COLOR }}
runs:
  using: "composite"
  steps:
    - name: Check existing images
      id: color
      shell: bash
      run: |
        # Authenticate with GHCR
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
        # Check if blue image exists and add debug output
        echo "Checking for existing blue image..."
        if docker manifest inspect ghcr.io/stevendejongnl/madebysteven:blue >/dev/null 2>&1; then
          echo "Blue image found, setting new color to green"
          NEW_COLOR="green"
          OLD_COLOR="blue"
        else
          echo "Blue image not found, setting new color to blue"
          NEW_COLOR="blue"
          OLD_COLOR="green"
        fi
        
        # Set outputs in the correct format
        echo "NEW_COLOR=${NEW_COLOR}" >> "$GITHUB_OUTPUT"
        echo "OLD_COLOR=${OLD_COLOR}" >> "$GITHUB_OUTPUT"
        
        # Debug: Show what we're setting
        echo "Color values being set:"
        cat $GITHUB_OUTPUT