env:
  browser: true
  es2020: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

overrides: 
  - files: [ "*.test.ts" ]
    rules:
      "@typescript-eslint/no-non-null-assertion":
        - off

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - '@typescript-eslint'

settings:
  "import/resolver":
    node:
      extensions:
        - ".js"

rules:
  indent:
    - error
    - 2
    - flatTernaryExpressions: false
      ignoredNodes:
      - "TemplateLiteral *"
      - PropertyDefinition[decorators]
      - TSUnionType
      - FunctionExpression[params]:has(Identifier[decorators])
  "@typescript-eslint/no-explicit-any":
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
