extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss

plugins:
  - stylelint-scss

overrides:
  - files: ['*.ts']
    customSyntax: postcss-lit

rules:
  at-rule-empty-line-before: null
  custom-property-empty-line-before: null

  color-hex-length: long
