language: php
php:
  - 7.1
  - 7.2

before_install:
- nvm install 10.11
- npm install -g gulp-cli

install:
- composer install
- npm install

script:
- gulp travis

cache:
  directories:
  - "node_modules"
  - "vendor"
