apiVersion: v1
kind: Namespace
metadata:
  name: madebysteven
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: madebysteven-blue
  namespace: madebysteven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madebysteven
      version: blue
  template:
    metadata:
      labels:
        app: madebysteven
        version: blue
    spec:
      containers:
      - name: madebysteven
        image: ghcr.io/stevendejongnl/madebysteven:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: madebysteven-green
  namespace: madebysteven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madebysteven
      version: green
  template:
    metadata:
      labels:
        app: madebysteven
        version: green
    spec:
      containers:
      - name: madebysteven
        image: ghcr.io/stevendejongnl/madebysteven:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: madebysteven-app
  namespace: madebysteven
spec:
  selector:
    app: madebysteven
    version: blue  # Change to 'green' to switch traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madebysteven-nginx
  namespace: madebysteven
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: www.madebysteven.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: madebysteven-app
            port:
              number: 80