apiVersion: apps/v1
kind: Deployment
metadata:
  name: madebysteven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madebysteven
  template:
    metadata:
      labels:
        app: madebysteven
    spec:
      containers:
      - name: madebysteven
        image: ghcr.io/stevendejongnl/madebysteven:latest
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: madebysteven-website
  namespace: madebysteven
spec:
  ingressClassName: nginx
  rules:
  - host: www.madebysteven.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rancher
            port:
              number: 80