name: Deploy
description: Deploy to GitHub Pages
runs:
  using: "composite"
  steps:
    - name: Move public to static-pages
      run: mv public static-pages

    - name: Copy CNAME to static-pages
      run: cp CNAME static-pages/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static-pages
