name: Deploy
description: Deploy to GitHub Pages
inputs:
  github-token:
    description: 'GitHub token for deployment'
    required: true
runs:
  using: "composite"
  steps:
    - name: Move public to static-pages
      run: mv public static-pages
      shell: bash

    - name: Copy CNAME to static-pages
      run: cp CNAME static-pages/CNAME
      shell: bash

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ./static-pages
