name: Build and Push Image
description: Build and push Docker image
inputs:
  github-token:
    description: 'GitHub token for ghcr.io'
    required: true
  color:
    description: 'Color tag for the image (blue/green)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and push image
      run: |
        docker build -t ghcr.io/stevendejongnl/madebysteven:${{ inputs.color }} .
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/stevendejongnl/madebysteven:${{ inputs.color }}
      shell: bash