name: Build and Deploy

on:
  push:
    branches:
      - master
  # workflow_run:
  #   workflows: ["Test"]
  #   types:
  #     - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14'

    - name: Install dependencies
      run: npm ci

    - name: Build CSS and compile TypeScript
      run: npm run build:css && npm run rollup

    - name: Move files and update paths
      run: npm run move-files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
