name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build CSS
      run: npm run build:css

    - name: Move index.html to dist
      run: mv index.html dist/

    - name: Update index.html paths
      run: sed -i 's/\.\/dist\///g' dist/index.html

    - name: Generate Rollup configuration
      run: |
        echo "import typescript from 'rollup-plugin-typescript2';" > rollup.config.js
        echo "" >> rollup.config.js
        echo "export default {" >> rollup.config.js
        echo "  input: 'src/main.ts'," >> rollup.config.js
        echo "  output: {" >> rollup.config.js
        echo "    file: 'dist/main.js'," >> rollup.config.js
        echo "    format: 'umd'," >> rollup.config.js
        echo "  }," >> rollup.config.js
        echo "  plugins: [" >> rollup.config.js
        echo "    typescript()," >> rollup.config.js
        echo "  ]," >> rollup.config.js
        echo "};" >> rollup.config.js

    - name: Build project
      run: npx rollup --config rollup.config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
