name: Build and Deploy

on:
  push:
    branches:
      - master
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15'

      - name: Install dependencies
        run: npm clean-install

      - name: Build application
        run: ./scripts/build.sh

      - name: Move files and update paths
        run: ./scripts/publish.sh ${{ github.ref }}

      - uses: actions/upload-artifact@master
        with:
          name: build
          path: public

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: build
          path: build-artifact

      - name: Copy to public directory
        run: cp -r build-artifact public

      - name: Deploy master to GitHub Pages (madebysteven.nl)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist

      - name: Deploy next to GitHub Pages (madebysteven.nl/next)
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/next'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
