name: Build and Deploy

on:
  push:
    branches:
      - master
      - next
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14'

    - name: Install dependencies
      run: npm ci

    - name: Build CSS and compile TypeScript
      run: npm run build:css && npm run rollup

    - name: Move files and update paths
      run: npm run move-files

    - name: Deploy master to GitHub Pages (madebysteven.nl)
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist

    - name: Deploy next to GitHub Pages (madebysteven.nl/next)
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/next'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        # destination_dir: next
