name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.8.1'

    - name: Install dependencies
      run: npm ci

    - name: Build CSS and compile TypeScript
      run: |
        npm run build:css
        npm install \
          rollup-plugin-typescript2 \
          rollup-plugin-postcss \
          @rollup/plugin-node-resolve \
          @rollup/plugin-replace \
          rollup-plugin-summary
        npx rollup --config rollup.config.js

    - name: Move files and update paths
      run: |
        mv CNAME dist/
        mv index.html dist/
        mv pages/* dist/
        sed -i 's/\.\/dist\///g' dist/index.html
        sed -i 's/..\/dist\///g' dist/*.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
