name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build CSS
      run: npm run build:css

    - name: Move index.html to dist
      run: mv index.html dist/

    - name: Update index.html paths
      run: sed -i 's/\.\/dist\///g' dist/index.html

    - name: Build project
      run: |
        npm install \
        rollup-plugin-typescript2 \
        rollup-plugin-google-fonts \
        rollup-plugin-postcss \
        @rollup/plugin-node-resolve \
        @rollup/plugin-replace \
        rollup-plugin-summary
        
        npx rollup --config rollup.config.js

    - name: Remove Google Fonts link
      run: sed -i '/<link href="https:\/\/fonts\.googleapis\.com\/css2?/d' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
