name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/action.yml
      - uses: ./.github/actions/playwright/action.yml
      - uses: ./.github/actions/deploy/action.yml